Add GET /api/books/search endpoint
Dimagaa/online-book-store pull request #3
Opened 2023-09-02 14:01 UTC by Dimagaa

Replace the existing BookRepository with the one that will use JpaRepository interface
Add Liquibase support
Change spring.jpa.hibernate.ddl-auto property value to validate
Implement soft delete concept for the Book entity
Add missing endpoints and methods for BookService

2023-09-04 18:20 UTC, ConfusedSatlan approved these changes
Good

2023-09-06 15:18 UTC, vovasalyha requested changes
GJ. Left few minor suggestions.

2023-09-06 15:18 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id = ?")
```

2023-09-06 15:18 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@Where(clause = "is_deleted = false")
```

2023-09-06 15:18 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/model/Book.java
>  public class Book {
It's recommended to override equals and hashcode for entities too.

2023-09-06 15:18 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
What if book by this id does not exist?

2023-09-06 15:38 UTC, Dimagaa commented on src/main/java/com/app/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
Good point!

2023-09-06 15:46 UTC, vovasalyha approved these changes
Approving, but please analyze my comment about update method.

2023-09-06 15:46 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/BookServiceImpl.java
> +        if (bookRepository.findById(id).isEmpty()) {
Yep, something like that, but more common approach is to fetch an entity and set new fields for this entity and then save it (or not save at all if you want to use hibernate's dirty checking feature, but in your case you are returning the updated entity, so it is better to explicitly save it to return actual data)

2023-09-06 16:06 UTC, merged

2023-10-30 11:27 UTC, andrii-hoienko reviewed
GJ! Let`s improve your solution

2023-10-30 11:27 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +        if (searchParameters.author() != null && searchParameters.author().length > 0) {
Please use already existing method like StringUtils.isEmpty()

2023-10-30 11:27 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +        if (searchParameters.title() != null && !searchParameters.title().isEmpty()) {
Please use already existing method like ArrayUtils.isNotEmpty()

2023-10-30 11:27 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +            specification = specification.and(bookSpecificationProviderManager
Blocks of code that add parameter to specification are very similar, maybe it is possible to extract common code to method?

2023-10-30 11:27 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/repository/book/BookSpecificationBuilder.java
> +    public Specification<Book> build(BookSearchParameters searchParameters) {
OPTIONAL: You can implement strategy here

2023-10-30 11:27 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id = ?")
Why old changes displayed here?