Add shopping cart
Dimagaa/online-book-store pull request #8
Opened 2023-09-14 15:37 UTC by Dimagaa

2023-09-15 16:15 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-15 16:15 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/model/CartItem.java
> +    @ManyToOne
make it lazy

2023-09-15 16:15 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/security/JwtUtil.java
> +            logger.error("Can't parse jwt: ", e);
```suggestion
            logger.warn("Expired or invalid JWT token");
```

2023-09-15 16:15 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-15 16:15 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-15 16:15 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/UserServiceImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
I suggest to extract a logic related to shopping cart to a private method

2023-09-18 14:07 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-18 14:07 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/controller/ShoppingCartController.java
> +                               @RequestBody CartItemUpdateRequestDto request) {
```suggestion
                               @RequestBody @Valid CartItemUpdateRequestDto request) {
```

2023-09-18 14:07 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/model/CartItem.java
> +    @ManyToOne
not resolved

2023-09-18 15:13 UTC, vovasalyha approved these changes

2023-09-18 15:25 UTC, merged